#!/bin/bash

# Navigate to the build folder
cd "$(dirname "$0")/../build" || { echo "Build folder not found"; exit 1; }

# Check if zb-gw-unify exists and run it
if [ -f zb-gw-unify ]; then
    ./zb-gw-unify
else
    echo "zb-gw-unify not found"
    exit 1
fi
